
# This file is automatically generated by setup.py
short_version = '3.0.5'
version = '3.0.5'
full_version = '3.0.5.dev-ad7d9c4'
git_revision = 'ad7d9c476d48077f7b34ad47718218f7ef13c476'
release = False

if not release:
    version = full_version
